#!/usr/bin/env bash

set -e

target="${1}"
shift
focused="$(chunkc tiling::query --desktop id)"

if [[ "${target}" == "${focused}" ]] ; then
  if [[ "$(chunkc tiling::query --desktop windows)" == "desktop" && -n "$@" ]] ; then
    exec "$@"
  else
    next="$(chunkc get _last_active_desktop)"
    if [[ "${next}" == "${focused}" ]] ; then
      echo TODO
    fi
    khd -p "alt + ctrl + cmd + shift - ${next}"
  fi
else
  khd -p "alt + ctrl + cmd + shift - ${target}"
  # have to wait for osx space-swapping animation
  sleep 0.5
  if [[ "$(chunkc tiling::query --desktop windows)" == "desktop" && -n "$@" ]] ; then
    exec "$@"
  fi
fi
