#!/bin/bash
set -e

bspc config border_width 2
bspc config window_gap 4

# subtract the gap plus border width from the
# edges of the screen, so that the edge of the
# screen is against the adjacent window with no
# separation
bspc config top_padding -6
bspc config bottom_padding -6
bspc config left_padding -6
bspc config right_padding -6

bspc config split_ratio 0.55
bspc config initial_polarity second_child

bspc config focus_follows_pointer true
bspc config focus_by_distance true

bspc config normal_border_color '#404040'
bspc config focused_border_color '#40a0ff'
bspc config presel_feedback_color '#ffffff'

# the default prefix is W, which you might not
# expect if you didn't know it was the default
# this actually returns -1 (not sure why) but
# it does work, so I silence the exit code
bspc config status_prefix '' || true

# give the first monitor its desktops:
# Terminal, Web, Misc
# this also resets the desktop, so that
# border/gap/padding config applies to it
bspc monitor ^1 -d T W M

bspc rule -a Firefox desktop=W
bspc rule -a Skype desktop=M
bspc rule -a mpv state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Pinentry state=floating
